name: pyrite
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - astroid=2.9.0
  - autopep8=1.6.0
  - blas=1.0
  - bottleneck=1.3.4
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - certifi=2022.5.18.1
  - cftime=1.5.1.1
  - curl=7.82.0
  - cycler=0.11.0
  - dbus=1.13.18
  - et_xmlfile=1.1.0
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - geographiclib=1.52
  - geopy=2.2.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=58.2
  - intel-openmp=2021.4.0
  - isort=5.9.3
  - jdcal=1.4.1
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libcurl=7.82.0
  - libcxx=12.0.0
  - libcxxabi=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - libzip=1.8.0
  - lz4-c=1.9.3
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - netcdf4=1.5.7
  - numexpr=2.8.1
  - numpy=1.22.3
  - numpy-base=1.22.3
  - olefile=0.46
  - openpyxl=3.0.9
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.4.2
  - patsy=0.5.2
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.4
  - platformdirs=2.4.0
  - pycodestyle=2.8.0
  - pylint=2.12.2
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - qt=5.9.7
  - readline=8.1.2
  - scipy=1.7.3
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.38.3
  - statsmodels=0.13.2
  - sympy=1.10.1
  - time=1.8
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - wrapt=1.13.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
